### ISSUE TITLE
How to get features written for behave-django to work in PyCharm?

### ISSUE THREAD

**Issue by dschweisguth** [behave/behave-django#26]
PyCharm has its own behave runner. Even with behave-django in the project, PyCharm's runner doesn't know how to hook up behave-django's database management or other features such as context.base_url. Is there a way to set up behave-django with an arbitrary runner, or would it require explicit support in behave-django or PyCharm or both?

Related:
- https://youtrack.jetbrains.com/issue/PY-21979
- http://stackoverflow.com/questions/41208517/how-to-run-behave-django-features-in-pycharm

**Comment by bittner** [comment]
Can you describe the behavior you expect from PyCharm? What is your personal use case? (Is it _Run Configurations_?)

Proprietary PyCharm helpers
-------------------------------

For what I can see, in PyCharm 2016.3.1 you can create a _Run Configuration_ of type _Behave_. PyCharm uses its own set of helper scripts to execute those, which rely on an installed `behave` module and probably on its default execution pattern:
``` python
/home/peter/.virtualenvs/painless-website/bin/python /opt/pycharm-2016.3/helpers/pycharm/behave_runner.py
Testing started at 23:54 ...
Traceback (most recent call last):
  File "/opt/pycharm-2016.3/helpers/pycharm/behave_runner.py", line 16, in <module>
    from behave.formatter.base import Formatter
ImportError: No module named 'behave'
```
With `behave` installed locally the output of a _Behave_ run configuration looks more like:
``` python
/home/peter/.virtualenvs/python-testing/bin/python /opt/pycharm-2016.3/helpers/pycharm/behave_runner.py
Testing started at 23:58 ...

Process finished with exit code 0
```
In other words, PyCharm relies on the "fact" that _behave_ is run via the `behave` shell command. However, with _behave-django_ we run a Django _management_ command to launch _behave_, which is how we integrate into Django and launch the `LiveServerTestCase`:
``` bash
$ python manage.py behave
```
I'm not quite sure what JetBrains would have to change to make this all work with `behave-django`. Simply running the management command from PyCharm may be one (part of the) solution.

Integration
-----------

Access to the [`base_url` or, better, to `get_url()`](https://github.com/behave/behave-django/blob/master/docs/usage.rst#web-browser-automation) only depends on running the management command. Those properties are attached dynamically by our code to the `context` variable _behave_ provides during a test run. They expose properties available from a Django `LiveServerTestCase` to the BDD test run.

**Comment by dschweisguth** [comment]
@bittner yes, the goal would be to get behave-django to work with PyCharm's run configurations. Performing actions that create run configurations (e.g. control-shift-R on a scenario or feature) should create run configuratons that run scenarios or features as if they'd been run from `python manage.py behave`.

I agree with your analysis: PyCharm would either need to run a management command or simulate that environment. Maybe behave-django would then just work.

**Comment by bittner** [comment]
Looks like we should vote for JetBrain's ticket [PY-20064](https://youtrack.jetbrains.com/issue/PY-20064) in order for this issue to get resolved.

I'm closing this issue as we can't do much from our side.

**Comment by dschweisguth** [comment]
@bittner thanks for handling this thoroughly!

**Comment by bittner** [comment]
@dschweisguth Thank _you_, for your time, your dedication and thoroughness!

**Comment by bittner** [comment]
I'm closing this issue as we actually can't do much about it. It's all up to JetBrains, they maintain their proprietary integration with `behave`.

Anyone interested in pushing an integration with PyCharm forward, please visit JetBrains issue [PY-21979](https://youtrack.jetbrains.com/issue/PY-21979) and ask them gently to resolve it.

**Comment by bittner** [comment]
Reopening this issue as we are discussing a sustainable solution with JetBrains here at [DjangoCon Europe 2017](https://2017.djangocon.eu/). See JetBrains issue [PY-21979](https://youtrack.jetbrains.com/issue/PY-21979) for additional details.

Brainstorming
------------

1. Currently, the only - "semi-official" - API `behave` is providing is hooks ([documentation](https://pythonhosted.org/behave/tutorial.html#debug-on-error-in-case-of-step-failures)).
1. Just for comparison, [pytest allows creating plugins](https://docs.pytest.org/en/latest/writing_plugins.html#setuptools-entry-points) via `entry_points` in setuptools (several plugins can be installed and executed for a single test run). This could be an elegant approach for `behave`, too.
1. If there is no proprietary implementation of hooking into `behave` (*read:* if there is an official API) the integration will be both slick and much more stable (*read:* new version of behave will take care integrations are backwards-compatible).
1. An API solution should make life easier for both PyCharm and behave-django (clean, official, documented approach of integrating into `behave`).

API Approach
---------

A `behave` plugin should have the ability to hook into the test execution process. This way:

1. you can start a Django instance before running the tests, -- *behave-django*
1. `behave` may read a `DJANGO_SETTINGS_MODULE` value from its config file, -- *behave-django* 
1. PyCharm can start its own protocol - via its own `behave` plugin available in the PyCharm installation, -- *PyCharm*
1. plugins should be able to consume behave's information regarding progress of test execution in real-time. -- *PyCharm*

@jenisys Does this sound reasonable? What are your thoughts about this?

**Comment by bittner** [comment]
@jenisys Did you have time to read over the proposal above? This needs acting on the `behave` side first (plugin architecture).

Would be cool if we can make this happen. Thanks!

**Comment by jenisys** [comment]
@bittner Sorry, for the late response.

API RELATED: 
Regarding points 1 and 2 (behave-django related)
1. Should already be possible with the existing implementation in "environment.py" (before_all hook) or in an own runner-script that starts the Django instance and calls ``behave main()``.
2. Should be possible in "environment.py" (before_all hook)

Regarding points 3 and 4 (PyCharm function points)
3. I am not quite sure why point 3 is needed (currently it should call behave script maybe with some own parameters like an own formatter).
4. SHOULD ALREADY BE SOLVED:
  PyCharm should already use its own formatter and use an existing one and parse the results

REGARDING: plugins
Plugins need defined points (extension-points) when they are used/activated. In addition, not every installed behave plugin should be automatically used, only the "enabled ones" for a test location.
Currently, only Formatters are supported (because this is a well-defined extension-point and there is a convincing need for it). As long as the problem can be solved without additional plugin-points (or "hooks"), I would first try to use it (because I do not see the selling point (yet)). With the ``before_all()`` (and using ``userdata`` as configuration mechanism) you should be able to inject most plugins with very few lines of code (best case: 1 line).

If you had something else in mind, we would need to discuss where you see the need for extension-points in the behave run and why.

**Comment by bittner** [comment]
The whole point of [our API approach suggestion](https://github.com/behave/behave-django/issues/26#issuecomment-291452201) is:

- we install a Python package ("behave plugin"),
- and all the integration we need is in place.

This is the actual problem we're trying to solve. Not the integration itself, but the package-driven integration. "We" is:

1. _behave-django_: Let developers use the `behave` command instead of a Django management command (or as a natural alternative to it). Make it easy for `behave` users to transfer their knowledge to Django projects, and avoid misunderstandings caused by "contradicting" documentation (behave, behave-django; e.g. see #15). 
1. _PyCharm_: Integrate into behave and Django in an automated fashion (e.g. install a package and configure it in a scripted way) without hacks that may break in the future. Control program flow and capture information about progress or `behave` output in order to display it in the IDE as progress information and/or indicators.

Why `environment.py` Is Not Enough
-------------------------------
It's of course possible to add integration code to `environment.py` to make things "just work". But, think this, if we were happy with that (i.e. happy with asking a developer to do _copy+paste of an integration code snippet_ into `environment.py`) `behave-django` wouldn't even exist. And for tool integration this approach, unfortunately, is clearly not working.

**Comment by throwable-one** [comment]
Hello.

@jenisys thank you for your idea about Formatters. PyCharm does not use them know, but definitely should do it.

How ever, it does not solve behave-django problem.
PyCharm launches behave directly and may provide itself as formatter, but behave-django does it as well and knows nothing about PyCharm.

What do you think about some environment variable like BEHAVE_FORMATTER? PyCharm may set it for any script it launches and Behave may use it to activate formatter automatically?

**Comment by jenisys** [comment]
@throwable-one 
The behave formatter problem is solvable. Behave supports multiple formatters during a test run. Therefore, it is be possible to inject an additional formatter by adding parameters on the command-line.

**Comment by jenisys** [comment]
@bittner 
A working proof-of-concept (POC) helps the discussion what is needed. From my understanding, it is possible by using the "environment.py" file and the existing hooks. If something is missing, it will also become clearer what is missing and where. Then, a second design can be made that implements the same functionality by using  plugins (and allows comparison to the first solution). We can discuss/finetune it until we have an agreeable solution (and identify the extension-points that are needed and for which a plugin can register itself).

**Regarding plugins injected automatically via installed packages:**
This does not work from my experience (and bites you in the back). For example, ``behave-django`` provides such a plugin (or several) and ``behave-django`` is installed. Therefore, the ``behave-django`` plugin is always and automatically used during each behave run. But now you have a case, where the behave tests do not use any django related functionality. We do no want that this plugin is automatically used when we are in this project/directory context.

Therefore, plugins installed with packages are OK (also the normal entry-point concept), but you need a configuration layer that allows the user to stay in control and enable only the plugins that are needed (and desired) in a specific test scope. As I have already said, the behave's userdata functionality could be used to provide transport-vehicle for such a configuration layer (from the command-line or configuration-file to the "environment.py" file). The acting logic that applies the configuration (for example to ``behave-django`` and/or ``django``) is still needed.

Any suggestions how to improve the discussion/development of such a concept are welcome (own playground project on Github to evolve the solution, Hangout meetings, Slack group, etc.).

**Comment by bittner** [comment]
@throwable-one, if there are any command line arguments you'd like to pass to *behave* (as of [your comment](https://youtrack.jetbrains.com/issue/PY-21979#comment=27-2265895) on YouTrack) then let us know here.

Ideally, simply place a PR with changes to the [behave management command](https://github.com/behave/behave-django/blob/master/behave_django/management/commands/behave.py) implementation to add command line arguments you'd need to register a formatter. Thanks!

**Comment by throwable-one** [comment]
Hello @bittner @jenisys 
I was able to install pycharm helper as formatter, but there is one problem: to support progress bar we need to know the number of steps, and the only way to find it is to run runner in ``dry_run`` mode and calculate number of steps. @jenisys do I miss something?

So you can't simply run ``behave -f __pycharm_formatter__``, so we can do the following:
* Сreate behave formatter for PyCharm and TeamCity (it could be part of https://github.com/JetBrains/teamcity-messages)
* We then migrate our runner to it and run in with dry mode before normal mode.
* You will simply use it as formatter (if ``teamcity-messages`` is installed and PyCharm is detected (we may provide some ENV var)) you pass ``-f __our_formatter_``. ``behave-django`` will have "fake" progress bar, but I believe this is not a really big issue for now.

What do you think?

**Comment by bittner** [comment]
I'm not sure how `behave-django` fits into this game ("_You will simply use it as formatter_"), I also don't understand the "_fake progress bar_".

If you want PyCharm and TeamCity to use `behave-django` you should be able to simply pass the formatter option to our management like this:
```
$ python manage.py behave -f __pycharm_formatter__
```
It should work the same way as using `behave` directly. Only that with `behave-django` installed the `behave` management command integrates into the Django project or application.

**Comment by throwable-one** [comment]
My first idea was to provide some environment variable to ``behave`` command asking to it to add pycharm formatter to list of arguments, but I agree we can simply run ``manage.py behave`` from PyCharm.

>I also don't understand the "fake progress bar".
PyCharm provides  progress bar that tells how many tests user has and how many tests are left.
To obtain number of tests, it first runs behave with ``--dry-run``, but it is not  how ``behave`` command works.

But after your comment I discussed it with collegues, and thats how we will support it:
We will stay with our ``behave`` integration but instead of ``behave`` we'll use ``manage.py behave`` with our formatter but only for people who has Django integration enabled and ``behave-django`` installed.

**Comment by bittner** [comment]
> To obtain number of tests, it first runs behave with `--dry-run`, but it is not how `behave` command works.

I think you could use behave's `--steps-catalog` option. Note that all behave options are directly available with `python manage.py behave`, too.

**Comment by throwable-one** [comment]
@bittner thank you.

@jenisys Could you please help me with formatters API?
It seems that *all* ``step()`` callbacks are called before actual step execution. And before execution it calls ``match()``, but match does not have link to step it actually matched. So, there is no way to say which step Behave is going to execute now.

Here is an example

```

Feature: Spam

  Scenario: Eggs
    Given I love BDD
    Then I use Behave

####
from behave import *

@given("I love BDD")
def step_impl(context):
    print("I love BDD executed")

@then("I use Behave")
def step_impl(context):
    print("I use behave executed")


####
from behave import runner, configuration
from behave.formatter import _registry
from behave.formatter.base import Formatter


class MyFormatter(Formatter):

    def feature(self, feature):
        print "Reported Feature" + str(feature)

    def scenario(self, scenario):
        print "Reported Scenario" + str(scenario)

    def step(self, step):
        print "Reported step" + str(step)

    def match(self, match):
        print "Reported match" + str(match)

    def result(self, step_result):
        print "Reported result" + str(step_result)


_registry.register_as("MyFormatter", MyFormatter)
cfg = configuration.Configuration()
cfg.log_capture = False
cfg.stdout_capture = False
cfg.format = ["MyFormatter"]
runner.Runner(cfg).run()
```

Here is my output

```
Reported Feature<Feature "Spam": 1 scenario(s)>
Reported Scenario<Scenario "Eggs">
Reported step<given "I love BDD"> # First step reported but NOT executed nor mateched yet
Reported step<then "I use Behave"> # Second step reported but NOT executed nor mateched yet
Reported match<Match step_impl, steps\steps.py:5> # Function will be executed now, but which step it belongs to?
I love BDD executed
Reported result<given "I love BDD">
Reported match<Match step_impl, steps\steps.py:10>
I use behave executed
Reported result<then "I use Behave">
```

PyCharm requires following sequence of envents:

* Feature started
* Scenario started
* Step1 started
* Step1 finished
* Step2 started
* Step2 finished
* Feature finished # this one 
* Scenario finished # and this one are very useful, but something we can live without


Since ``match()`` is called by step, we may have ``match(match, step)`` signature (and use ``formatter.match(match, self)`` to call it) but that may break API. We may also add ``step`` field to ``Match`` class and it seems to be safe. If you have plans on 1.2.6 I can send you PR.
Or do we have some other approach to solve this?

**Comment by jenisys** [comment]
The formatter already has the knowledge and is normally not stateless. Therefore, if you need this information store it in ``Formatter.step()`` to be accessible in ``Formatter.match()``. The occurs in other cases, too. For example, how do you in which feature you are when scenario is called ?

Example:

```python
class MyFormatter(Formatter):
...
    def step(self, step):
        self.current_step = step
        ...

    def match(self, matchObject):
         do_something_with_step(matchObject, self.current_step)

    def result(self, result):
        ...
        self.current_step = None   # Invalidate step data again.
```

NOTES:
* The matchObject has a reference to the step-function that is matched by a step-definition
* Look at the PrettyFormatter implementation
* Use ``repr(matchObject)`` instead of ``str(matchObject)``
* ``Formatter.step()`` is called before the step is executed
* ``Formatter.result()`` is called after the step is executed and the outcome (result) is known
* ``Formatter.eof()`` marks end-of-feature: See [JsonFormatter.eof()](https://github.com/behave/behave/blob/master/behave/formatter/json.py#L185)
* ``Formatter.close()`` marks end-of-testrun

Otherwise, look at the implementation of other formatters.

In your example of events for PyCharm is an error. The scenario is (implicitly) finished before the feature is finished. Reason: Symmetry

**Comment by throwable-one** [comment]
Hm.. as I can see in my example *all* ``step()``s are called *before* first match, so if I store them in ``current_step`` I will stay with the last one.

```
class MyFormatter(Formatter):

    def step(self, step):
        self.current_step = step

    def match(self, matchObject):
        print("Current step" + repr(self.current_step))

    def result(self, result):
        self.current_step = None  # Invalidate step data again.
```
output

```
Current step<then "I use Behave">
I love BDD executed
Current stepNone
I use behave executed
```

You can see same problem in my snippet:
```
Reported step<given "I love BDD"> # First step reported but NOT executed nor mateched yet
Reported step<then "I use Behave"> # Second step reported but NOT executed nor mateched yet
Reported match
```

Since steps are executed in the order they are detected, I can use queue here, and it works
```
class MyFormatter(Formatter):
    def __init__(self, stream_opener, config):
        super(MyFormatter, self).__init__(stream_opener, config)
        self.__steps = deque()

    def step(self, step):
        self.__steps.append(step)

    def match(self, matchObject):
        print("Current step" + repr(self.__steps.popleft()))
```

Output is correct:
```
Current step<given "I love BDD">
I love BDD executed
Current step<then "I use Behave">
I use behave executed
```

Did I misunderstand something?

> The scenario is (implicitly) finished before the feature is finished

Yes, thank you. I assume that scenario is finished in case of ``eof`` or next ``scenario``.

**Comment by jenisys** [comment]
@throwable-one 
Queue or List for steps sounds correct. It has beed some time since I implemented my last formatter ;-(
As I said, use the existing formatters to gain a better understanding.

**Comment by bittner** [comment]
See JetBrain's issue [PY-21979](https://youtrack.jetbrains.com/issue/PY-21979#comment=27-2726315) for details on how behave integration is finally managed, which may be included in one of the next releases of PyCharm.
