### ISSUE TITLE
no context.base_url

### ISSUE THREAD

**Issue by LetishaB** [behave/behave-django#31]
I have 0.4.1 behave-django with 1.2.5 behave, and splinter installed, but context has no base_url, nor get url or anything like that.

it has the following:
`['BEHAVE', 'USER', '__class__', '__contains__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__gt__', '__hash__', '__init__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_config', '_dump', '_emit_warning', '_mode', '_origin', '_pop', '_push', '_record', '_root', '_runner', '_set_root_attribute', '_stack', 'execute_steps', 'user_mode']`

**Comment by bittner** [comment]
Please share more details:

- How you invoke behave?
- How you integrate/use behave-django?
- Technical details of your setup (e.g. `INSTALLED_APPS`, etc.)
- A sample test to reproduce the error

It sounds like you don't have `'behave_django'` in your `INSTALLED_APPS`, and run your tests with `$ behave` (instead of `$ python manage.py behave`), but we need more info about your setup to verify this assumption.

**Comment by LetishaB** [comment]
I was using PyCharm's behave module, when I ran it with the manage.py command runner it worked fine! Didn't think it would be that different. Thanks for the quick response. Is there a way to have the PyCharm's test runner work with behave_django? That would be nice! :)

**Comment by bittner** [comment]
Unfortunately not, not at the moment. This all depends on JetBrains. Please see issue #26 for details.

If you would visit JetBrains issue [PY-21979](https://youtrack.jetbrains.com/issue/PY-21979) and gently ask them to resolve it that may help to get this problem fixed.
