### ISSUE TITLE
Scenario Independence

### ISSUE THREAD

**Issue by bkuehlhorn** [behave/behave-django#55]
In Feature `Fixture loading`, I switch the first two Scenarios: `Load fixtures' and `Load fixtures for this scenario and feature'. The new second scenario fails. Scenarios should not pass because they run on specific order. Scenarios should be total independent.

Scenario `Load fixtures for this scenario and feature` violates scenario independence by:
```
        context.fixtures.append('behave-second-fixture.json')
```

Fixture append is permanent update to Feature and impacts remaining scenarios.

I write test scenarios to be independent and run in random order.

**Comment by bittner** [comment]
What would your proposed change to `behave-django` look like?

Would you mind preparing a pull request?

**Comment by bkuehlhorn** [comment]
Submitted https://github.com/behave/behave-django/pull/56 to fix Scenario that change Feature Fixtures.

**Comment by bittner** [comment]
PR #56 was closed by request of the PR and issue author. Is there a proper way to get this topic resolved? Maybe add an explanation of the behavior to the [related docs](https://behave-django.readthedocs.io/en/stable/fixtures.html)?

We should otherwise close this issue.

**Comment by bittner** [comment]
The documentation explains how [test isolation](https://behave-django.readthedocs.io/en/stable/isolation.html) is handled in `behave-django`. A related note in the [Fixture Loading](https://behave-django.readthedocs.io/en/stable/fixtures.html#fixtures-in-environment-py) chapter gives additional hints. Fixtures are meant to be loaded before each scenario. This approach ensures proper isolation.

If this is perceived to be counter-intuitive or otherwise problematic please explain and/or submit a PR that improves the situation.
