### ISSUE TITLE
Send-email testing with mail.outbox

### ISSUE THREAD

**Issue by yaseralnajjar** [behave/behave-django#73]
I've written this simple test:

```python
@when('asking for review and saving')
def act(self):
    site = Site(domain='http://127.0.0.1:8000', name='127.0.0.1')
    site.save()

    request = {'SITE_ID': site.id}
    self.asking_reservation = {'reservation_id': self.reservation1.id}
    self.deserialized_data = AskForReviewSerializer(
        data=self.asking_reservation, context={'request': request})


@then('validate data and send email for review asking')
def test(self):
    with freeze_time(self.reservation_creation_date_plus_two_months):
        assert self.deserialized_data.is_valid() == True
        assert len(mail.outbox) == 0

        self.deserialized_data.save()
        assert len(mail.outbox) == 1
```

And this is the serializer I'm testing which sends an email when saving:

```python
class AskForReviewSerializer(serializers.Serializer):
    reservation_id = serializers.IntegerField()

    def save(self, *args, **kwargs):
        request = self.context.get('request')

        current_site = get_current_site(request)
        reservation_id = self.validated_data['reservation_id']

        reservation = models.Reservation.objects.get(pk=reservation_id)
        if not reservation.is_reviewable:
            raise serializers.ValidationError('This reservation is not reviewable')

        user = reservation.user

        path = f'/reservations/{reservation_id}/review'
        url = settings.BASE_URL + path
        context = {'current_site': current_site,
                   'user': user,
                   'review_url': url,
                   'request': request}

        get_adapter().send_mail(
            'review/email/ask_for_review',
            user.email,
            context)

    class Meta:
        fields = ('reservation_id', )
```

But `mail.outbox` is never affected when running the tests, its length is always zero (I ensured that my EMAIL_BACKEND = 'django.core.mail.backends.locmem.EmailBackend')

Full test: https://github.com/coretabs/dorm-portal/blob/master/features/steps/reviews.py#L117

Any idea how can I test the email sending behavior using behave-django?

**Comment by bittner** [comment]
I'm not exactly sure what would be the shortest way to helping you, but at first sight I see a few issues with your code:

1. Your step implementation should have a first argument called `context`. In your code this is always `self`. While this is not strictly a technical problem it may obscure the way to find a solution yourself. -- **Use `context` as the first argument**, the steps are functions not methods (see [examples](https://github.com/behave/behave-django/blob/master/tests/acceptance/steps/django_test_client.py#L10) in the project repo).
1. I'm not sure what you're doing with `Site`. Can't you use Django's test client, which saves you from hard-coding URL values and such?
1. You're importing `mail` [at the top of the module](https://github.com/coretabs/dorm-portal/blob/master/features/steps/reviews.py#L5), I think that's wrong. You should access the mail object that the Django test client has access to. It sounds obvious that otherwise the object is never populated.
1. Instead of manually creating a client instance and URLs you should be able to move some of the code into the [behave setup code](https://github.com/behave/behave-django/blob/master/tests/acceptance/environment.py) and call `context.get_url(...)`.

I like the way you call your step implementation functions (`act`, `test`), though! :+1:

**Comment by yaseralnajjar** [comment]
First, thanks for the fast response!

> Use context as the first argument

I've changed all the `self` into `context`, thanks for the tip!

> I'm not sure what you're doing with Site

I just fixed that as well, it's not related with the test client; it's actually related with `current_site = get_current_site(request)` in the AskForReviewSerializer since I wanna check the reviewing-url sent in the email (it should start with http://127.0.0.1:8000).

> You're importing mail at the top of the module

I saw it in the django docs: https://docs.djangoproject.com/en/2.1/topics/testing/tools/#email-services, is there something that I'm missing? How can I access the mail object that the Django test client has access to?

> Instead of manually creating a client instance and URLs you should be able to move some of the code into the behave setup code

I'll try to refactor the tests once I finish the reviews and room-management features.

Thanks a lot for reviewing the code (would appreciate any other comments) :pray:

**Comment by bittner** [comment]
The example in the Django documentation you quote uses a Django `TestCase`, maybe this makes a difference for `mail.outbox`. You can access Django's test client from the `context` as [described in our docs](https://behave-django.readthedocs.io/en/latest/usage.html), via `context.test.client`.

What returns `context.get_url('/reservations/')`? Doesn't it yield `http://127.0.0.1:8000/reservations/`?

**Comment by yaseralnajjar** [comment]
> What returns context.get_url('/reservations/')? Doesn't it yield http://127.0.0.1:8000/reservations/?

It actually returns `http://localhost:61626/reservations/` :confused:

> You can access Django's test client from the context as described in our docs, via context.test.client.

I understand, but how would that help me affecting `mail.outbox`?

I searched a bit and I realized that BehaviorDrivenTestCase inherits from the StaticLiveServerTestCase which eventually inherits from TestCase:
https://github.com/django/django/blob/master/django/contrib/staticfiles/testing.py
https://github.com/django/django/blob/master/django/test/testcases.py

What would be the reason that `mail.outbox` is not affected?

Is there any workaround to get the mail.outbox populated during the test? or should I rely on the fact the serializer doesn't throw any exception and keep it as it is?

**Comment by bittner** [comment]
> I searched a bit and I realized that BehaviorDrivenTestCase inherits from the StaticLiveServerTestCase which eventually inherits from TestCase

That is correct. That's why you should use `context.test.client` if you want to access the Django `TestCase` that is launched by behave-django. Then the `mail.outbox` behavior should match what is described in the Django docs you quote..

> Is there any workaround to get the mail.outbox populated during the test? or should I rely on the fact the serializer doesn't throw any exception and keep it as it is?

I believe, there is a conceptual misunderstanding you're trapped in. You should understand the way behave works (because behave-django is just marrying behave with Django), and how this affects writing tests for DRF, which you're obviously using. Maybe you could take a look at similar issues (such as #46) and do some research on how [writung testing with DRF](https://www.django-rest-framework.org/api-guide/testing/). I just found out there is a dedicated project called [behave-restful](https://github.com/behave-restful/behave-restful), maybe that makes your job easier? Not sure though.

**Comment by yaseralnajjar** [comment]
> I believe, there is a conceptual misunderstanding you're trapped in

I felt that there are too many gaps that I need to fill :confounded: 

> I just found out there is a dedicated project called behave-restful, maybe that makes your job easier? Not sure though

Thanks for the recommendation... I've looked into it, there is no specific problem it tackles with no docs (I use django-behave mainly to test the logic, validate the (de)serialization, and only check the response status code given the right request data).

I'm gonna come back to this once I finish the room management feature... thanks a lot for your help!
