### ISSUE TITLE
Raises sqlite3.IntegrityError: FOREIGN KEY constraint failed when all tests run successfully

### ISSUE THREAD

**Issue by faran-mw** [behave/behave-django#80]
I run all tests using "./manage.py test" command and I have a combination of behave and non-behave tests. They all run successfully but I get the above exception in the end during the teardown step. Does anybody have any idea about a solution/workaround?

**Comment by bittner** [comment]
Since you're not running the tests with the management command provided by this package (i.e. `python manage.py behave`), I'm afraid this is not exactly the right place to discuss your issue.

I'd suggest to post your question in a more generic forum, e.g.
- [Django's Gitter room](https://gitter.im/django/django),
- [Behave's Gitter room](https://gitter.im/behave/behave),
- some other, [official discussion resource](https://www.djangoproject.com/community/) of the Django community.

Don't forget to provide _more context_, e.g. source code and command line or IDE details on how you execute your tests, to make it easier to help you with questions or direct suggestions.

Thank you for your understanding!
