### ISSUE TITLE
Fixtures loaded via decorator do not always reset between scenarios

### ISSUE THREAD

**Issue by DolanMaize** [behave/behave-django#92]
If running two scenarios that each load different fixtures ***and*** `context.fixtures` is already defined (e.g. in `before_all` or `before_feature`), then the fixtures loaded in the first scenario remain in the context for the second scenario.

For example, in the following setup, the "Testing 2" scenario would have fixtures "somedata.json", "test1.json", and "test2.json" loaded:
```
def before_all(context):
    context.fixtures = ['somedata.json']

############

@fixtures('test1.json')
@given('I have test1 data')
def step_impl(context):
    pass

@fixtures('test2.json')
@given('I have test2 data')
def step_impl(context):
    pass

############

Scenario: Testing 1
    Given I have test1 data

Scenario: Testing 2
    Given I have test2 data
```

**Comment by bittner** [comment]
Could you try the [traditional approach](https://behave-django.readthedocs.io/en/stable/usage.html#fixture-loading) (environment.py) to verify whether the behavior is different? That would be helpful to know.

**Comment by bittner** [comment]
Looking at the code I'd find it worth trying to understand why we set `registered_fixtures` instead of `context.fixtures` with the decorator:

* in [environment.py](https://github.com/behave/behave-django/blob/master/behave_django/environment.py#L73-L74)
* in [decorators.py](https://github.com/behave/behave-django/blob/master/behave_django/decorators.py#L15)

According to the [documentation](https://behave-django.readthedocs.io/en/stable/usage.html#fixtures-using-a-decorator) the behavior should be identical:

> The decorator will load the fixtures in the `before_scenario`, as documented above.

According to the source code it doesn't seem so, though.

@jenisys Is there a relevant fact that I'm overlooking?

**Comment by DolanMaize** [comment]
@bittner - Currently working on a PR for this; the fix that works for me is to copy `context.fixtures` when assigning it to `context.test.fixtures`.
